### ISSUE TITLE
virtual host path in the example is misleading

### ISSUE THREAD

**Issue by bishnupradhan** [groall/rabbitmq-http-api-client-php#1]
$client = new \RabbitMqHttpApiClient('localhost', 15672, 'login', 'password');
$queueInfo = $client->queueInfo('\\', 'queueName');

here, vhost path (Name of an individual virtual host), getting an error as Object Not Found.
I have placed '/' instead of '\\' as vhost path in my local system. which is working fine.

**Comment by groall** [comment]
thank you 
I've fixed the readme
